# Generated by Django 5.2 on 2025-09-09 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="分类")),
            ],
            options={
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
                "db_table": "blog.categote",
            },
        ),
        migrations.CreateModel(
            name="BlogContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="博客标题")),
                ("content", models.TextField(verbose_name="博客内容")),
                (
                    "time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="博客发布时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="博客作者",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.categote",
                        verbose_name="文章分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "发布博客",
                "verbose_name_plural": "发布博客",
                "db_table": "blog.Content",
            },
        ),
        migrations.CreateModel(
            name="BlogCommit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(auto_now_add=True, verbose_name="评论时间"),
                ),
                ("commit", models.TextField(verbose_name="评论内容")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评论作者",
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.blogcontent",
                        verbose_name="博客作者",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论内容",
                "verbose_name_plural": "评论内容",
                "db_table": "blog.Commit",
            },
        ),
    ]
